language: php
dist: trusty

php:
  - 7.2

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --prefer-dist
  - npm install && npm run production

script:
  - vendor/bin/phpunit

notifications:
  email: false
